src/main.ts
src/modules/common/dto/error.dto.ts
src/modules/common/exception-filter/all-exceptions.filter.ts

Close #9 
모든 에러를 핸들링하는 Filter를 추가했습니다 !
에러코드는 console.log로 출력시켜놓은 상태인데, 해당 부분은 차후에 Logger 선정해서 Install 하여 붙이는걸로 하겠습니다

Error Handler 구현

---

src/modules/api.module.ts
src/modules/generation/controller/generation.controller.ts
src/modules/generation/dto/create-generation.dto.ts
src/modules/generation/dto/reponse-generation.dto.ts
src/modules/generation/dto/update-generation.dto.ts
src/modules/generation/generation.module.ts
src/modules/generation/repository/generation.repository.ts
src/modules/generation/service/generation.service.ts

Close #8 
Generation CRUD 작업 완료했습니다!
Feature/9 ( All-Exception )와 함께 사용 되는 코드가 있어서 둘다 머지 해야 정상적으로 구동됩니다 :)
중간에 Github Commit을 기능별로 안해놨는데, 다음번 커밋부턴 기능별로 하겠습니다~

Generation 모듈 작업

---

.github/workflows/deploy.yml

jwt 및 password 기능 추가로 인한 환경 변수 & github secret key 추가 설정
없음

Fix: Add password & jwt env value

---

.github/workflows/auto-author-assign.yml

feat: pr 생성시 자동으로 author 생성 action추가

---

.github/workflows/deploy.yml

Close #1
- Github Workflow 오타 수정

style: AccessKey 오타 수정

---

src/modules/common/exception-filter/all-exceptions.filter.ts
src/modules/generation/controller/generation.controller.ts
src/modules/generation/service/generation.service.ts

- 지원 기수 및 활동 기수 반환 오류 해결
- 예외처리 부분 리펙토링

현재 기수 반환 문제 해결

---

src/modules/user/controller/user.controller.ts
src/modules/user/service/user-admin.service.ts
src/modules/user/service/user.service.ts
src/modules/user/user.module.ts

Close 
userService, adminService 구분

refactor: userService, admin service 구분

---

src/infra/entity/Applications.entity.ts

feat: 최종 제출 여부를 담당하는 컬럼 추가

---

src/modules/part/controller/part.controller.ts

fix: 조회에 권한이 필요 없도록 수정

---

src/infra/entity/Applications.entity.ts
src/modules/part/controller/part.controller.ts

조회에 권한이 필요 없도록 버그 수정

---

src/modules/application/application.module.ts
src/modules/auth/role/rolesType.ts
src/modules/generation/service/generation.service.ts
src/modules/part/part-base.module.ts
src/modules/part/service/part-base.service.ts
src/modules/question/dto/create-question.dto.ts
src/modules/question/dto/get-questions.dto.ts
src/modules/question/service/question.service.ts
src/modules/user/controller/user.controller.ts
src/modules/user/service/user-admin.service.ts
src/modules/user/service/user-base.service.ts
src/modules/user/service/user.service.ts

Close #이슈번호
@annahxxl 누나가 작업할 수 있도록 중간 저장

Feat/application transaction 까지 저장

---

src/infra/entity/Applications.entity.ts
src/modules/application/application-base.module.ts
src/modules/application/application.module.ts
src/modules/application/controller/application.controller.ts
src/modules/application/repository/answer.repository.ts
src/modules/application/service/application-base.service.ts
src/modules/application/service/application.service.ts
src/modules/generation/service/generation.service.ts
src/modules/part/controller/part.controller.ts

Feat/application 임시 swagger 추가 배포

---

src/modules/application/service/application-base.service.ts
src/modules/application/service/application.service.ts

feat: 타입 오류 수정// todo: 타입만 수정한 버전

---

src/infra/entity/Applications.entity.ts
src/modules/application/dto/create-application.dto.ts
src/modules/application/service/application-base.service.ts

feat: status enum으로 관리

---

src/modules/application/controller/application.controller.ts
src/modules/application/dto/create-application.dto.ts
src/modules/application/dto/update-application.dto.ts
src/modules/application/service/application-base.service.ts
src/modules/application/service/application.service.ts
src/modules/part/service/part-base.service.ts
src/modules/user/service/user-base.service.ts

Feat/application 임시 dto 추가

---

src/modules/user/controller/user.controller.ts
src/modules/user/service/user-admin.service.ts
src/modules/user/service/user.service.ts

feat(User): user쪽에서 유저에 모든 지원서 가져오는 기능 추가

---

src/modules/application/service/application.service.ts
src/modules/common/common.module.ts
src/modules/common/common.service.ts
src/modules/question/service/question.service.ts

feat: transaction 을 공통 모듈로 분리

---

src/infra/entity/Applications.entity.ts
src/modules/application/controller/application.controller.ts
src/modules/application/dto/update-application.dto.ts
src/modules/application/service/application-admin.service.ts
src/modules/application/service/application-base.service.ts
src/modules/application/service/application.service.ts
src/modules/common/common.service.ts

Feat/application 지원 기능 완료

---

src/core/swagger/swagger.type.ts
src/modules/portfolio/controller/portfolio.controller.ts

Fix: file 저장시 발생하는 문제 해결

---

src/infra/entity/Questions.entity.ts
src/modules/question/dto/create-question.dto.ts
src/modules/question/service/question.service.ts

fix: 타입 수정

---

src/infra/entity/Questions.entity.ts

feat: required 속성을 추가한다

---

src/app.module.ts
src/modules/application/controller/application.controller.ts
src/modules/application/service/application-base.service.ts
src/modules/application/service/application.service.ts

Feat/questions 임시 저장 답변 중복 생성 문제 수정

---

.platform/nginx/conf.d/set_limit_size.conf

- Nginx의 설정을 변경하는 파일 추가
- 경로 /.platform/nginx/conf.d

AWS EB의 Nginx 용량 제한으로 인한 413 문제 해결

---

.ebextensions/set_limit_size.config
.platform/nginx/conf.d/set_limit_size.conf

Nginx 문제 이슈 반영

---

.ebextensions/set_limit_size.config
.platform/nginx/conf.d/elasticbeanstalk/proxy.conf
.platform/nginx/conf.d/set_limit_size.conf

- .platform/nginx/conf.d/elasticbeanstalk 으로 conf 파일 경로 변경
- client_body_buffer_size 버퍼 사이즈 제한 변경

Fix: Nginx 설정파일 변경

---

.platform/nginx/conf.d/elasticbeanstalk/proxy.conf
.platform/nginx/conf.d/proxy.conf

Nginx conf 파일 수정

---

.github/workflows/deploy.yml
.platform/00_myconf.config
.platform/nginx/conf.d/proxy.conf

- Github Actions Workflow에 .platform 파일 추가

Fix: Deploy Workflow에 .platform 파일 첨부 및 용량제한 삭제

---

.github/workflows/deploy.yml

Fix:Dir인식 오류 해결

---

src/modules/application/service/application.service.ts
src/modules/part/controller/part.controller.ts
src/modules/part/part.module.ts
src/modules/part/service/part.service.ts

fix: 빠진 기능 수정

---

src/modules/application/service/application.service.ts

fix: partId 도 참조하도록 변

---

src/modules/question/domain/long-question.strategy.ts
src/modules/question/domain/short-question.strategy.ts

fix: 멍청한 실수 복구

---

src/modules/application/repository/application.repository.ts

fix: application 쪽 쿼리에 데이터 빠진 부분 추가

---

src/modules/question/domain/checkBox-question.strategy.ts

fix: 체크박스의 경우 선택지가 없도록 수정한다

---

src/modules/application/repository/application.repository.ts
src/modules/application/service/application.service.ts

Fix/question 질문 해결

---

.ebextensions/00-set-timezone.config
src/modules/generation/service/generation.service.ts

Fix: Timezone 이슈 해결
